"""
Enumerations for Resource Bank models.

Features:
- 006-resource-bank: GeneratedByType, LLMProvider, MasteryLevel, PersonalizationStyle
- 007-resource-bank-files: ResourceType, Visibility, S3SyncStatus, AddedBy

Created: 2025-12-27
"""

from enum import Enum as PyEnum


# Feature 006 Enums


class GeneratedByType(str, PyEnum):
    """Who generated the explanation (system admin or student with own API key)."""

    SYSTEM = "system"  # v1 explanations generated by admin
    STUDENT = "student"  # v2+ explanations generated by student with their API key


class LLMProvider(str, PyEnum):
    """LLM provider for AI generation."""

    ANTHROPIC = "anthropic"  # Claude Sonnet 4.5 (primary)
    OPENAI = "openai"  # GPT-4.5 (fallback)
    GEMINI = "gemini"  # Gemini (fallback)


class MasteryLevel(str, PyEnum):
    """Student mastery progression for learning path tracking."""

    NOT_STARTED = "not_started"  # Topic not viewed yet
    LEARNING = "learning"  # Initial view, in progress
    FAMILIAR = "familiar"  # Viewed 3+ times, building confidence
    MASTERED = "mastered"  # High confidence, ready to move on


class PersonalizationStyle(str, PyEnum):
    """Teaching style personalization for explanations."""

    DETAILED = "detailed"  # PhD-level depth with all examples
    CONCISE = "concise"  # Summarized key points only
    VISUAL = "visual"  # Diagram-heavy with visual aids
    PRACTICE_FOCUSED = "practice_focused"  # More practice problems


# Feature 007 Enums


class ResourceType(str, PyEnum):
    """Type of learning resource stored in the Resource Bank."""

    SYLLABUS = "syllabus"
    TEXTBOOK = "textbook"
    PAST_PAPER = "past_paper"
    VIDEO = "video"
    ARTICLE = "article"
    USER_UPLOAD = "user_upload"


class Visibility(str, PyEnum):
    """Access control visibility for resources (multi-tenant isolation)."""

    PUBLIC = "public"  # Visible to all students (approved resources)
    PRIVATE = "private"  # Only visible to uploader + admin
    PENDING_REVIEW = "pending_review"  # Admin + uploader only (awaiting approval)


class S3SyncStatus(str, PyEnum):
    """S3 background upload status tracking."""

    PENDING = "pending"  # Queued for upload
    SUCCESS = "success"  # Successfully uploaded to S3
    FAILED = "failed"  # Upload failed after retries
    PENDING_RETRY = "pending_retry"  # Failed, queued for retry batch


class AddedBy(str, PyEnum):
    """Source of resource-to-syllabus-point tagging."""

    SYSTEM = "system"  # Auto-linked by system (e.g., official syllabus always linked)
    ADMIN = "admin"  # Manually tagged by admin via tagging interface
    STUDENT = "student"  # Tagged by student (for own learning path customization)
