"""Add attempts and attempted_questions tables for Phase II

Revision ID: 002b_attempts
Revises: 002_questions
Create Date: 2025-12-20

Phase II missing tables - tracks student exam attempts and question-level responses.

Tables created:
- attempts: Links students to exams, tracks start/submit times, scores
- attempted_questions: Individual question responses within an attempt

Constitutional Requirements:
- Principle V: Multi-tenant isolation (student_id FK with CASCADE DELETE)
- Principle II: A* grading (grade enum, overall_score)

Architecture Decision:
- Separate attempts from exams to allow multiple attempts per exam template
- Question-level granularity for detailed feedback and progress tracking
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic
revision: str = '002b_attempts'
down_revision: Union[str, Sequence[str], None] = '002_questions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Create attempts and attempted_questions tables

    Tables:
    1. attempts - Student exam attempts (many-to-one with exams)
    2. attempted_questions - Question-level responses (many-to-one with attempts)
    """

    # ========================================================================
    # Create attempts table
    # ========================================================================

    op.create_table(
        'attempts',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('student_id', UUID(as_uuid=True), sa.ForeignKey('students.id', ondelete='CASCADE'), nullable=False),
        sa.Column('exam_id', UUID(as_uuid=True), sa.ForeignKey('exams.id', ondelete='CASCADE'), nullable=False),
        sa.Column('started_at', sa.DateTime, nullable=False, server_default=sa.text('NOW()')),
        sa.Column('submitted_at', sa.DateTime, nullable=True),
        sa.Column('overall_score', sa.Integer, nullable=True),  # Total marks awarded
        sa.Column('grade', sa.String(5), nullable=True),  # A*, A, B, C, D, E, U
        sa.Column('status', sa.String(20), nullable=False, server_default="'IN_PROGRESS'"),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.text('NOW()')),
        sa.Column('updated_at', sa.DateTime, nullable=True),

        # Check constraints
        sa.CheckConstraint("status IN ('IN_PROGRESS', 'SUBMITTED', 'GRADED')", name='ck_attempts_status'),
        sa.CheckConstraint("grade IN ('A*', 'A', 'B', 'C', 'D', 'E', 'U') OR grade IS NULL", name='ck_attempts_grade'),
        sa.CheckConstraint('overall_score >= 0 OR overall_score IS NULL', name='ck_attempts_overall_score')
    )

    # Create indexes on attempts
    op.create_index('idx_attempts_student_id', 'attempts', ['student_id'])
    op.create_index('idx_attempts_exam_id', 'attempts', ['exam_id'])
    op.create_index('idx_attempts_status', 'attempts', ['status'])
    op.create_index('idx_attempts_created_at', 'attempts', ['created_at'])

    # ========================================================================
    # Create attempted_questions table
    # ========================================================================

    op.create_table(
        'attempted_questions',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('attempt_id', UUID(as_uuid=True), sa.ForeignKey('attempts.id', ondelete='CASCADE'), nullable=False),
        sa.Column('question_id', UUID(as_uuid=True), sa.ForeignKey('questions.id', ondelete='CASCADE'), nullable=False),
        sa.Column('student_answer', sa.Text, nullable=True),  # Nullable if unanswered
        sa.Column('marks_awarded', sa.Integer, nullable=True),  # Null until marked
        sa.Column('marking_feedback', JSONB, nullable=True),  # {errors: [], strengths: [], suggestions: []}
        sa.Column('weaknesses', JSONB, nullable=True, server_default=sa.text("'[]'::jsonb")),  # Array of weakness categories
        sa.Column('model_answer', sa.Text, nullable=True),  # A* exemplar (generated by Reviewer Agent)
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.text('NOW()')),
        sa.Column('updated_at', sa.DateTime, nullable=True),

        # Unique constraint: One answer per question per attempt
        sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempted_questions_attempt_question'),

        # Check constraint: marks_awarded cannot be negative
        sa.CheckConstraint('marks_awarded >= 0 OR marks_awarded IS NULL', name='ck_attempted_questions_marks')
    )

    # Create indexes on attempted_questions
    op.create_index('idx_attempted_questions_attempt_id', 'attempted_questions', ['attempt_id'])
    op.create_index('idx_attempted_questions_question_id', 'attempted_questions', ['question_id'])

    # GIN index on weaknesses array for fast containment queries
    op.create_index(
        'idx_attempted_questions_weaknesses',
        'attempted_questions',
        ['weaknesses'],
        postgresql_using='gin'
    )


def downgrade() -> None:
    """
    Rollback attempts and attempted_questions tables

    CAUTION: This will delete all student attempt data.
    """

    # Drop indexes first
    op.drop_index('idx_attempted_questions_weaknesses', table_name='attempted_questions')
    op.drop_index('idx_attempted_questions_question_id', table_name='attempted_questions')
    op.drop_index('idx_attempted_questions_attempt_id', table_name='attempted_questions')

    op.drop_index('idx_attempts_created_at', table_name='attempts')
    op.drop_index('idx_attempts_status', table_name='attempts')
    op.drop_index('idx_attempts_exam_id', table_name='attempts')
    op.drop_index('idx_attempts_student_id', table_name='attempts')

    # Drop tables in reverse order (respect foreign keys)
    op.drop_table('attempted_questions')
    op.drop_table('attempts')
