openapi: 3.0.3
info:
  title: Resource Bank - Tagging & Search API
  version: 1.0.0
  description: Resource tagging to syllabus points and keyword search

paths:
  /api/resources/{id}/tag:
    post:
      summary: Link resource to syllabus point with relevance score
      tags: [Tagging]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [syllabus_point_id, relevance_score]
              properties:
                syllabus_point_id:
                  type: string
                  format: uuid
                relevance_score:
                  type: number
                  minimum: 0
                  maximum: 1
      responses:
        '201':
          description: Resource tagged successfully

  /api/resources/search:
    get:
      summary: Full-text keyword search
      tags: [Tagging]
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Search results with ranking
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    resource_id:
                      type: string
                      format: uuid
                    title:
                      type: string
                    rank:
                      type: number
                      description: Search relevance score

  /api/syllabus/{point_id}/resources:
    get:
      summary: Auto-select resources for syllabus point (by relevance score)
      tags: [Tagging]
      parameters:
        - name: point_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Auto-selected resources sorted by relevance
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    resource_id:
                      type: string
                      format: uuid
                    title:
                      type: string
                    relevance_score:
                      type: number
